appConfig:
  microservice:
    identity-provider:
      url: "https://authority.be.{{ .Values.namespaceTag.authority }}.{{ .Values.authorityDomainSuffix | default .Values.domainSuffix }}"
  open-id-connect:
    certs-endpoint: "https://authority.be.{{ .Values.namespaceTag.authority }}.{{ .Values.authorityDomainSuffix | default .Values.domainSuffix }}/auth/realms/authority/protocol/openid-connect/certs"

  spring:
    profiles:
      active: "participant"
    data:
      redis: 
        port: "6379"
        username: "default"