global:
  profile: participant
autoscaling:
  enabled: false
keycloak:
  master:
    user: admin
    realm: participant
  clientToRealmRoleMigration:
    enabled: true
    clientIds: '[''frontend-cli'']'
databaseSeeding:
  roleIdentityAttributesMapping:
    enabled: true
    filePath: null
appConfig:
  spring:
    liquibase:
      contexts: test
