global:
  profile: participant
autoscaling:
  enabled: false
keycloak:
  master:
    user: admin
    realm: participant
  clientToRealmRoleMigration:
    enabled: true
    clientIds: '[''frontend-cli'']'
databaseSeeding:
  roleIdentityAttributesMapping:
    enabled: true
    filePath: null
appConfig:
  spring:
    liquibase:
      contexts: test
  notification:
    role-requests:
      my-profile-url: https://participant.fe.{{ .Values.namespaceTag.consumer }}.{{
        .Values.domainSuffix }}/users-roles/my-profile
      role-request-review-page: https://participant.fe.{{ .Values.namespaceTag.consumer
        }}.{{ .Values.domainSuffix }}/users-roles/role-requests-management/review/{roleRequestId}
