apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: consumer-deployer
spec:
  project: default
  source:
    repoURL: https://code.europa.eu/api/v4/projects/903/packages/helm/stable
    path: '""'
    targetRevision: 3.0.0-F-feature-splits.882.bfd7a890
    helm:
      parameters:
        - name: consumer_iaa.extraValues.tier1_gateway.targetRevision
          value: 2.7.0
      values: |
        project: default
        namespaceTag: 
          authority: authority
          consumer: consumer
          common: common
        domainSuffix: org-x.helsinki.tfds.io
        authorityDomainSuffix: ds.helsinki.tfds.io
        argocd:
          appname: consumer
          namespace: argocd
        cluster:
          address: https://kubernetes.default.svc
          namespace: consumer
          commonToolsNamespace: common
          issuer: dev-prod
        secrets:
          role: example-role
          secretEngine: example
        monitoring:
          enabled: false
        consumer_iaa:
          extraValues:
            tier2_gateway:
              targetRevision: 2.7.0  
        resourcePreset: low
    chart: consumer
  destination:
    server: https://kubernetes.default.svc
    namespace: consumer
