#Domain associated with Cluster
domain: integrated.simpl-europe.eu

# enable ingress only for development purpose
# on production environment this service must be exposted through the participant tier1 gateway only
ingress:
  enabled: false

log4j:
  level:
    # logging level for all logs excluding the specific ones
    root: INFO
    # logging level for application components only
    app: DEBUG
    # logging level for feign clients only
    feign: DEBUG

web:
  mvc:
    cors:
      # optional allowed origins for cross calls (list separed by comma or * to allow all origins)
      # if empty no cross calls are allowed
      allowedOrigins: ""

    bearerToken:
      # if true a JWT token must be present as Bearer in any request
      required: true
      # optional list (comma separated) of allowed paths (ant matcher expressions) to skip JWT token check (ex: actuator health paths)
      allowedPaths: "/actuator/health/*,/status"

# comma separated list of servers url to be used by swagger
openapiConfig:
  servers: https://contract-consumption-be.integrated.simpl-europe.eu

# url to the connector adapter internal service
connectorAdapter:
  service:
    url: http://edc-connector-adapter:8080

# configuration for connectivity between Contract-Consumption-Be and Validation
validation:
  config:
    enabled: true
     # domain is the URL of SDTooling-Api-Validation service
    # (sdtool-validation is name of Kube service associated. Check it!)
    domain:  http://sd-validation:8080
    # name of Validation API Method
    validationResourceAddressApiV1: "/v1/resourceAddress/validate"